version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    name: 'Approval check'
    validate:
      - do: approvals
        min:
          count: 2 # Number of minimum reviewers. In this case 2.
        #required:
        #  reviewers: [ 'matthias-roussel-soyhuce', 'matthiasrsl' ]
        #  owners: true
        limit:
            teams: [] 
            users: ['matthias-roussel-soyhuce', 'matthiasrsl']
