version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    name: 'Approval check'
    validate:
      - do: approvals
        min:
          count: 1
        limit:
            teams: [] 
            users: ['matthias-roussel-soyhuce']
      - do: changeset
        must_exclude:
          regex: ".github/"
