version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    name: 'Approval check'
    validate:
      - do: approvals
        limit:
          users: [ 'matthias-roussel-soyhuce', 'dlaugiersoyhuce' ]
          owners: true
