version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    name: 'Approval check'
    validate:
      - do: approvals
        required:
          reviewers: [ 'matthias-roussel-soyhuce', 'matthiasrsl' ]
          owners: true
